name: CI with k6

on:
  push:
    branches:
      - main  # Ou outra branch de sua preferência

jobs:
  k6-tests:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout do código
      - name: Check out repository
        uses: actions/checkout@v2

      # Instalar k6
      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      # Instalar jq (caso não esteja disponível)
      - name: Install jq
        run: sudo apt-get install jq

      # Instalar mailutils para envio de e-mails
      - name: Install mail client
        run: sudo apt-get install mailutils

      # Rodar os testes com k6
      - name: Run k6 load test
        id: k6-test
        run: |
          k6 run test.js --out json=results.json --summary-export=summary.json  # Adicionando o summary-export para gerar o summary.json

      # Comparar os resultados com o baseline e enviar e-mail em caso de falha
      - name: Compare with baseline and send email if failed
        run: |
          BASELINE_REQUESTS=200  # Número esperado de requests
          BASELINE_AVG_RESPONSE_TIME=1000  # Tempo médio de resposta esperado (em ms)
          BASELINE_RQPS=10  # Exemplo de baseline de requests por segundo

          # Obter os dados consolidados do summary.json
          TOTAL_REQUESTS=$(jq '.metrics.requests.count' summary.json)
          AVG_RESPONSE_TIME=$(jq '.metrics.http_req_duration.avg' summary.json)
          RQPS=$(jq '.metrics.requests.rate' summary.json)
          ERROR_RATE=$(jq '.error_rate' summary.json)

          # Inicializar uma variável de mensagem de erro
          ERROR_MESSAGE="Falha nos testes de desempenho! Resultados abaixo do esperado:"

          # Comparar os valores e adicionar a falha correspondente à mensagem de erro
          if [ "$TOTAL_REQUESTS" -lt "$BASELINE_REQUESTS" ]; then
            ERROR_MESSAGE="$ERROR_MESSAGE\n- Número de requests abaixo do esperado: Esperado >= $BASELINE_REQUESTS, Obtido: $TOTAL_REQUESTS"
            echo $ERROR_MESSAGE
          fi

          if [ "$(echo "$AVG_RESPONSE_TIME > $BASELINE_AVG_RESPONSE_TIME" | bc -l)" -eq 1 ]; then
            ERROR_MESSAGE="$ERROR_MESSAGE\n- Tempo médio de resposta acima do esperado: Esperado <= $BASELINE_AVG_RESPONSE_TIME, Obtido: $AVG_RESPONSE_TIME"
            echo $ERROR_MESSAGE
          fi

          if [ "$(echo "$RQPS < $BASELINE_RQPS" | bc -l)" -eq 1 ]; then
            ERROR_MESSAGE="$ERROR_MESSAGE\n- Requests por segundo abaixo do esperado: Esperado >= $BASELINE_RQPS, Obtido: $RQPS"
            echo $ERROR_MESSAGE
          fi

          if [ "$(echo "$ERROR_RATE > 0" | bc -l)" -eq 1 ]; then
            ERROR_MESSAGE="$ERROR_MESSAGE\n- Taxa de erro acima do esperado: Esperado = 0, Obtido: $ERROR_RATE"
            echo $ERROR_MESSAGE
          fi

          # # Verificar se algum parâmetro falhou e enviar o e-mail
          # if [ -n "$ERROR_MESSAGE" ]; then
          #   echo -e "$ERROR_MESSAGE" | \
          #     mail -s "Alerta de Teste de Desempenho" -S smtp="smtp://$SMTP_SERVER:$SMTP_PORT" \
          #     -S smtp-auth=login -S smtp-auth-user=$SMTP_USER -S smtp-auth-password=$SMTP_PASS \
          #     seu-email@dominio.com
          #   exit 1
          # else
          #   echo "Teste de desempenho aprovado!"
          # fi
